### PR TITLE
add bimdata class to custom scrollbar

### PR DESCRIPTION
**Pull request by LrxGaelle**
- [x] I have tested my component
- [ ] I have updated the documentation or there is no documentation needed

### CODE REVIEW

**Review by Amoki — APPROVED** [review]

**Comment by LrxGaelle** [comment]
/!\ breaking change
by adding a class, it means that we will have to add it on all our current projects,

**Review by NicolasRichel — COMMENTED** [review]
This is nice !
Can you explain how it is intended to be used ?

**Comment by LrxGaelle** [comment]
This means that, with these changes, we will have to use the `.bimdata-scrollbar` class on **every root component of our other projects** (which will want to use this custom scrollbar and 'branding' bimdata)

**Comment by Amoki** [comment]
how does it work for plugins like BimObject. As they're in the viewer, it will work or we have to add a class in every plugins?

**Pull request merged**
