### PR TITLE
PATCH: chore: keep only the most used file icons

### PR DESCRIPTION
**Pull request by NicolasRichel**
- [ ] I have tested my component
- [ ] I have updated the documentation or there is no documentation needed

## Libraries that use the DS (need to merge first)

- [ ] [BCF Components](https://github.com/bimdata/bcf-components)
- [ ] [BIMData Components](https://github.com/bimdata/bimdata-components)
- [ ] [Building maker](https://github.com/bimdata/building-maker)

## Repos that use the DS (and that I need to check after libraries have been merged)

- [ ] [Viewer](https://github.com/bimdata/viewer)
- [ ] [Platform](https://github.com/bimdata/platform)
- [ ] [SDK](https://github.com/bimdata/bimdata-viewer-sdk)
- [ ] [Marketplace](https://github.com/bimdata/marketplace-front)
- [ ] [Documentation](https://github.com/bimdata/documentation)

Voici la liste des extensions qui ont été conservées (24 au total):
 - .bmp
 - .csv
 - .doc
 - .docx => .doc
 - .dwg
 - .dxf
 - .e57
 - .ifc
 - .jpeg
 - .jpg => .jpeg
 - .las
 - .laz
 - .mp3
 - .mp4
 - .pdf
 - .png
 - .ppt
 - .pptx => .ppt
 - .sql
 - .svg
 - .txt
 - .xls
 - .xlsx => .xls
 - .zip

### CODE REVIEW

**Comment by GabBimdata** [comment]
Il manque les formats nuage de point. 
- e57 
- Laz
- Las
- Ply
- xyz
- pts
- xyzrgb
- xyzn
- pcd

Si ils sont dispos dans la lib (ce que je ne sais pas) je suis preneur.

**Comment by Amoki** [comment]
If we want to optimize a bit more, we could use the same icon for jpeg and jpg, xls and xlsx, doc and docx, etc

**Review by GabBimdata — APPROVED** [review]

**Pull request merged**
